### ISSUE TITLE
BUNDLE and payload values constraint

### ISSUE THREAD

**Issue by ibc** [ibc/mediasoup#18]
According to BUNDLE draft, if the same payload value appears more than twice in m= lines belonging to the same BUNDLE group, then those codecs MUST be the very same.

Not yet completely clear what would happen if the same transport is used to receive the same codec (payload, parameters, etc) from different participants (H264 video from Alice, from Bob, from Carol, etc).

* Thread open in MMUSIC WG: http://www.ietf.org/mail-archive/web/mmusic/current/msg16017.html
* Thread open in AVTCORE WG: https://mailarchive.ietf.org/arch/msg/avt/D-zKnht0xKJl6LKWa91FVstKXCw
* Also reported in ORTC: https://github.com/openpeer/ortc/issues/407

**Comment by ibc** [comment]
[draft-ietf-rtcweb-rtp-usage](https://tools.ietf.org/html/draft-ietf-rtcweb-rtp-usage-25) says, in section 4.3:

>  A single RTP payload type number MUST NOT be assigned to different
   RTP payload formats, or different configurations of the same RTP
   payload format, within a single RTP session (note that the "m=" lines
   in an SDP bundle group [I-D.ietf-mmusic-sdp-bundle-negotiation] form
   a single RTP session).

**Comment by ibc** [comment]
More related info:

* https://www.ietf.org/mail-archive/web/avt/current/msg17042.html

**Comment by ibc** [comment]
Plan:

* When joining a room, a peer must provide its "capabilities".
* Each room will handle an internal map of codecs (being each "codec" a codec name + specific configuration) indexed by a unique PT assigned to them.
* When in SDP, mediasoup will answer the SDP offer with (may be) modified PT values (to match the values in the map).
* When SDP re-offer is sent to a peer mediasoup will place the PT of its internal map, but the remote peer may decide to receive other PTs (it can do that in the SDP answer) so a PT mapping is required in each `RtpSender`.

/cc @jmillan

**Comment by jmillan** [comment]
:+1:

**Comment by ibc** [comment]
Very useful comment from Magnus in AVT mailing list:

>
So, I would like to make sure that we are on a common understanding what a SFU have to do with the RTP streams to make it possible to re-use the PTs.
>
So if we start with A and B communicating across an SFU. I will continue this from your example when you raised this in MMUSIC:
>
1) mid: alice-audio,  codec: opus,  payload: 100, ssrc: 1111
2) mid: bob-audio,   codec: g722,  payload: 100, ssrc: 2222
>
This would mean that Carol receives an SDP with two "m=audio"
sections using BUNDLE:
>
```
  m=audio [...] 100
  a=sendonly
  a=mid:alice-audio
  a=rtpmap:100 opus/48000/2
  a=ssrc:1111 cname:foo
  [...]
  m=audio [...] 100
  a=sendonly
  a=mid:bob-audio
  a=rtpmap:100 g722/48000
  a=ssrc:2222 cname:bar
  [...]
```
>
So from my perspective what the conference signalling server has to send Carol is an SDP that looks like this:
>
This would mean that Carol receives an SDP with two "m=audio"
sections using BUNDLE:
>
```
  m=audio [...] 100
  a=sendonly
  a=mid:alice-audio
  a=rtpmap:100 opus/48000/2
  a=ssrc:1111 cname:foo
  [...]
  m=audio [...] 101
  a=sendonly
  a=mid:bob-audio
  a=rtpmap:101 g722/48000
  a=ssrc:2222 cname:bar
  [...]
```
>
Then the SFU will need to change all RTP packets with PT=100 from Bob to PT=101 when forwarding them to Carol. The packets from Alice it can leave unchanged from an PT perspective.
>
If David joins the session and can do both codecs and offers like this:
>
```
m=audio [...] 98 99
a=sendrecv
a=rtpmap:98 opus/48000/2
a=rtpmap:99 g722/48000
a=ssrc:4444 cname:groo
```
>
Then I expect the conference server to determine that these configurations are identical to already existing ones and answer:
>
```
m=audio [...] 98
a=sendonly
a=mid:alice-audio
a=rtpmap:98 opus/48000/2
a=ssrc:1111 cname:foo
[...]
m=audio [...] 99
a=sendonly
a=mid:bob-audio
a=rtpmap:99 g722/48000
a=ssrc:2222 cname:bar
[...]
m=audio [...] 98 99
a=sendonly
a=mid:carol-audio
a=rtpmap:98 opus/48000/2
a=rtpmap:99 g722/48000
a=ssrc:3333 cname:skog
[...]
m=audio [...] 100 101
i=M block for David's audio stream
a=recv
a=rtpmap:100 opus/48000/2
a=rtpmap:101 g722/48000
```
>
So the SFU will translate the PTs towards Dave, to match what Dave accepts receiving. The SFU request Dave's endpoint to use the PTs it has defined as its common reception table out of the ones the Dave support.
>
Yes, using RTP middleboxes and SDP offer/answer do result in that one will have to specific PT values in use on each leg. It is very difficult to get this aligned to between the legs.
>
Your proposal is one way to avoid that translation. Which would require certain changes and issues. Another possibility would be to try to address it in the signalling system. Because having the possibility for the central controller to dictate the actual configuration within the capabilities of the endpoints would simplify certain things. Unfortunately both have issues to resolve and significant legacy inertia.

**Comment by ibc** [comment]
UPDATE: After a good chat with @jmillan, the room will be provided with mandatory `videoCodec` and `audioCodec` parameters so endpoints MUST support them and MUST use them (and no other codecs). Period.

Still we need a internal list of "valid" audio/video codecs in *mediasoup*. The list (to be completed) would start with:

* Audio:
  * opus
  * alaw
  * ulaw

* Video:
  * VP8
  * H264 packetization-mode=0
  * H264 packetization-mode=1

**Comment by saghul** [comment]
If 2 different endpoints use different H264 profile-level-id attributes someone will get confused, I'm afraid.

**Comment by ibc** [comment]
> If 2 different endpoints use different H264 profile-level-id attributes someone will get confused, I'm afraid.

Right. That's why mediasoup will not just consider codec name but codec+configuration units (not sure how to name them... perhaps `CodecUnit`).

Please check this 100% related comment: https://github.com/ibc/mediasoup/issues/19#issuecomment-200332092

So, as stated above, "H264" is not a "valid" codec. Instead there will be "H264 packetization-mode=0" and "H264 packetization-mode=1", which are considered different "codec units".

**Comment by saghul** [comment]
The profile-level-id can also make H264 codecs different. A low powered device might not be able to handle the "high" profile, for example.

On the implementations I've worked with, we always accept whatever the remote wants, but I guess this need not be the case for eveyone.

**Comment by ibc** [comment]
If so, different `profile-level-id` values would also generate different `codec units`. May you please detail those values?

**Comment by saghul** [comment]
They could. There are different [profiles](https://en.wikipedia.org/wiki/H.264/MPEG-4_AVC#Profiles) and [levels](https://en.wikipedia.org/wiki/H.264/MPEG-4_AVC#Levels). Also check https://tools.ietf.org/html/rfc6184#section-8.1

**Comment by ibc** [comment]
PLZ PLZ HELP

**Comment by ibc** [comment]
For example, as shown in #19, Firefox offers two H264 configurations:

```
a=rtpmap:126 H264/90000
a=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1

a=rtpmap:97 H264/90000
a=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1
```

Does it mean that it does not support other `profile-level-id`?

**Comment by saghul** [comment]
> Does it mean that it does not support other profile-level-id?

No. Those 2 configurations use the same profile-level-id, but different packetization-mode, hence the need for 2 configs.

**Comment by ibc** [comment]
Moving comments to #19 where they suit better.
