### ISSUE TITLE
use case about mediasoup

### ISSUE THREAD

**Issue by notedit** [ibc/mediasoup#24]
hi，

mediasoup is a greate lib, and i can't wait to have a try.

my use case is that  at  least two publisher and  tens of viewer in one room,  can mediasoup be used like this?

**Comment by ibc** [comment]
If *mediasoup* couldn't handle that use case it would be useless :)

BTW: I'm building the website (still under construction). You can check the Overview and API sections to get a better vision of what *mediasoup* will be:

http://mediasoup.org

**Comment by notedit** [comment]
thanks,  i will try mediasoup next week.

**Comment by ibc** [comment]
It won't be ready next week
