### ISSUE TITLE
can not find a way to make webrtc api work with mediasoup  api

### ISSUE THREAD

**Issue by notedit** [ibc/mediasoup#25]
mediasoup api  is  designed for ortc, it seems that  the signalingServer only need to handle candidates.

webrtc still need to offer/answer sdp info， can you give me an example how to make webrtc and mediasoup work?

**Comment by ibc** [comment]
Hi, mediasoup is not yet published nor completed, so I cannot help right now because the API is not finished.

**Comment by ibc** [comment]
BTW mediasoup will not handle SDP blobs. That's a task of a separate library. My aim is to let the API of mediasoup as clean as possible.

**Comment by notedit** [comment]
ok  i want to use android webrtc native client talk to mediasoup.  what's your plan about this separate library?

**Comment by ibc** [comment]
Someone (including me) may create a separate Node library that takes a SDP as input and generates the corresponding **mediasoup** API calls. But I prefer not to comment about that until I finish the mediasoup API.

**Comment by notedit** [comment]
https://github.com/webrtc/adapter/blob/master/src/js/edge/edge_shim.js

this is a shim from ortc to webrtc.   i am working on  a adapte  ortc to webrtc.

waiting for  mediasoup 1.0.

**Comment by ibc** [comment]
If adaptar.js has a ortc-to-webrtc shim I expect it also includes a webrtc-to-ortc shim. Otherwise it is useless. Do I miss something?
