### ISSUE TITLE
Server as peer to process decoded video frames

### ISSUE THREAD

**Issue by logidelic** [ibc/mediasoup#30]
Hey,

This looks like an awesome module. I'm about to dig in deep, but before I do, just want to make sure it can do what I'm hoping:

I'd like my Node server to act as a WebRTC peer and allow me to process decoded video frames in real time on the server.

Is it doable? Any pointers in the right direction? I've started reading through the code in mediasoup/test, but am still not quite sure where I might be able to get access to the video stream.

Thanks!

**Comment by ibc** [comment]
*mediasoup* won't decode video frames but just SRTP packets. Those RTP packets can be handled by the JavaScript application:

* http://mediasoup.org/api/#rtpReceiver-on-rtpraw
* http://mediasoup.org/api/#rtpReceiver-on-rtpobject

But, as stated above, *mediasoup* won't decode a opus or vp8 stream.
