### ISSUE TITLE
Usage Example/Getting Started Documentation

### ISSUE THREAD

**Issue by joegesualdo** [ibc/mediasoup#31]
# What?

Readme needs a usage example for people interested in getting started with the package

# Why?
Would love to test drive this package but it's lacking clear explanation of how to get started. Would be great if this could be added to the `README` or the website. 
> Note: The api documentation is great but not the best reference for getting started.

**Comment by joegesualdo** [comment]
This would also be solved if you had code for an example project.

**Comment by ibc** [comment]
There is incoming documentation. It will be published once the first release in out.

**Comment by Globik** [comment]
And how src directory co- works  with node.js? Can't see any node.h If require('./mediasoup-server') then must be mediasoup-server.node file. Should I run main.exe and then run node.exe server.js all together?

**Comment by ibc** [comment]
You should not care about the src directory at all. You just install mediasoup and use it via Node by following its API.

Also, check this: http://mediasoup.org/faq/#is-mediasoup-a-native-addon

**Comment by Globik** [comment]
@ibc  many thanx. Please tell me what kind of a file extension have the mediasoup-worker* ? so, exe, node? First time in linux world.. but the command file outputs 'lsb executables'

**Comment by igordata** [comment]
When you start a server with debug you can see worker's PID number in console. PID is Process ID. You can find this PID in the process list and get all the info you want.

**Comment by mirkobrankovic** [comment]
Hi, I do agree that example is more than needed to get people involved here

**Comment by ibc** [comment]
Regarding the new WebRTC 1.0 API, there is already doc and usage example:

http://mediasoup.org/api/#webrtc

**Comment by moppymopperson** [comment]
The link provided in the post above is broken, just a heads up.
