### ISSUE TITLE
Performace comparison 

### ISSUE THREAD

**Issue by airwave-development** [ibc/mediasoup#32]
I would like to see a performance comparison to other sfu's

**Comment by saghul** [comment]
Based on what criteria? Throughput, CPU usage, stream count per room, relayed bytes per second?

**Comment by notedit** [comment]
@airwave-development   still not 1.0 release yet.

**Comment by notedit** [comment]
@saghul  have you run a demo with mediasoup?  

i still does not make it.

**Comment by airwave-development** [comment]
Hi. Of course when the code is mature enough. Would be nice to see something like https://jitsi.org/Projects/JitsiVideobridgePerformance

**Comment by saghul** [comment]
That's indeed a great reference, thanks!

**Comment by notedit** [comment]
@airwave-development 

ibc  said that there is a  release this  weekends.

i will give a test  if  mediasoup has 1.0  release.

**Comment by ibc** [comment]
I will close this issue since there is no room to make a "performance comparison". mediasoup handles RTP in C/C++ baed on libuv. It's just very fast.

In the other side, we are working on proper RTCP support. Without proper RTCP support mediasoup is not ready to work nicely, so we prefer to wait until RTCP is done before releasing it.

**Comment by Globik** [comment]
Hi @airwave-development !  On my windows machine very nice perfomance!!!! One connection - one user for l'eternite!!! Great, хули, 1 connection for always and deadlock. Great job.

**Comment by ibc** [comment]
@Globik what do you mean? **mediasoup** does not work in Windows! That's clearly stated in the website:

http://mediasoup.org/overview/#requirements

> * Node.js >= v4.0.0
* POSIX based operating system (Windows not yet supported)
* Python 2
* make
* gcc or clang with C++11 support

So please, stop saying stupid things.
