### ISSUE TITLE
Should depend on python2

### ISSUE THREAD

**Issue by ibc** [ibc/mediasoup#33]
@saghul should this `configure.py` require python2?:

https://github.com/ibc/mediasoup/blob/master/worker/scripts/configure.py#L1

**Comment by saghul** [comment]
Yes.  GYP is Python 2 only.

**Comment by notedit** [comment]
there is no python2 on mac ,  i change that to python  makes it work.

**Comment by saghul** [comment]
That's a problem, yeah.  Not all platforms work with that shebang.  I'd leave it as "python" and perform a runtime check:

~~~~
if sys.version_info[0] != 2:
    raise RuntimeError('Python 2 is required')
~~~~

**Comment by ibc** [comment]
My `/usr/bin/python` in OSX has version "2.7.10". 

Also, when installing via `brew install python` it install "2.7.11" and places both `python` and `python2` in `/usr/local/bin/`, both are links that point to links that finally point to `/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7`.

In Debian 8.3 it happens the very same.

So I would replace `#!/usr/bin/env python2` with `#!/usr/bin/env python` in `configure.py`, but that would fail if `env python` points to Python3, right @saghul?

Please, note that such a script is directly invoked from a `make` command when executing the main [Makefile](https://github.com/ibc/mediasoup/blob/master/Makefile).

**Comment by ibc** [comment]
It seems that this could also work, but requires an extra step that I don't like:

```bash
$ npm config set python /usr/bin/python2.7  // or whatever
```

**Comment by ibc** [comment]
@saghul, will you send a PR soon regarding [gyp.js](https://github.com/indutny/gyp.js)?

**Comment by saghul** [comment]
> So I would replace #!/usr/bin/env python2 with #!/usr/bin/env python in configure.py, but that would fail if env python points to Python3, right @saghul?

Correct.  One such system is Arch Linux or the latest Ubuntu.

**Comment by saghul** [comment]
> will you send a PR soon regarding gyp.js?

Not anytime soon, I'm afraid :-S Sorry!

**Comment by ibc** [comment]
I want my money back!

**Comment by notedit** [comment]
i think this will work well

```

That's a problem, yeah. Not all platforms work with that shebang. I'd leave it as "python" and perform a runtime check:

if sys.version_info[0] != 2:
    raise RuntimeError('Python 2 is required')

```

**Comment by ibc** [comment]
One problem I see is:

The host has both python2 and python3, and `env python` points to python2. Then `#!/usr/bin/env python` would just fail.

In the other side, in a fresh OSX (no brew installed) python2 is installed by default, it provides `/usr/bin/python` but it does not provide `/usr/bin/python2`...
