### ISSUE TITLE
Two same files in different directories: for what?

### ISSUE THREAD

**Issue by Globik** [ibc/mediasoup#34]
Hi, trying to compile mediasoup on the windows machine and wondering, what for needing two the same files in different directories. One is https://github.com/ibc/mediasoup/blob/master/worker/src/Channel/UnixStreamSocket.cpp
And one is https://github.com/ibc/mediasoup/blob/master/worker/src/handles/UnixStreamSocket.cpp
Now unresolved symbols I have about unixstreamsocket::Close(void)

**Comment by saghul** [comment]
MediaSoup does not currently support Windows, I'm afraid.

**Comment by ibc** [comment]
They are not the same file at all.

BTW: Windows is not yet supported: http://mediasoup.org/overview/#requirements

**Comment by Globik** [comment]
Yes, I see. Is your implementation based on vanilla BSD socket or on a libuv wrapper socket?

**Comment by ibc** [comment]
It's based on libuv.
BTW: I do know that, in order to run in Windows, some stuff must be added (such an implementation of `getopt`) but I don't understand the unresolved symbol above. Note that mediasoup requires C++11 or C++14.

**Comment by Globik** [comment]
Yes, it is understandable. Most of libs(libuv, openssl, srtp, usctp etc) are windows friendly. Getopt, pthread, sigaction api there are third parties code variants near to bsd-like. Very intreresting in mediasoup code(for test and learn purposes), on windows machine.
My problem, not yours, those unresove symbols. I 'm at a very begining.

**Comment by ibc** [comment]
If you find the cause of that issue, let me know. In the future I'll like for *mediasoup* to run on Windows too.

**Comment by Globik** [comment]
Compiling good enough after some work on source code. But I am not really C++ programmer. 
Is not clear to me what for grammar.rl and IP.rl in utils folder, why there are also the same names of a few cpp and header files, for example unixstreamsocket.h tcpserver.cpp 2 instances.
As a result I came up, runned the tests, test_server.js works like a hero, but others with no luck.
Always says: error ocured timeout and channel is closed.
Also unclear to me how to change posix pthread_sigmask to windows friendly analog.
And this uv loop... how much loops is there within mediasoup instances: 2, 3 or much more?

**Comment by saghul** [comment]
> Also unclear to me how to change posix pthread_sigmask to windows friendly analog.

@ibc I don't think you need pthread_sigmask, since libuv handles signals on its own and calls your callback in the loop, you will never find yourself in a signal handler.

> And this uv loop... how much loops is there within mediasoup instances: 2, 3 or much more?

@Globik One per core in the system.

**Comment by saghul** [comment]
https://github.com/ibc/mediasoup/pull/35 should help a bit.

**Comment by ibc** [comment]
> Is not clear to me what for grammar.rl and IP.rl in utils folder,

Those are [Ragel](http://www.colm.net/open-source/ragel/) grammar files. They are converted into C++ source files before pushing to the github repo, so just forget them.

> why there are also the same names of a few cpp and header files, for example unixstreamsocket.h tcpserver.cpp 2 instances.

What is the problem?

* `handles/TCPServer.cpp` is a libuv C++ wrapper for a TCP server.
* `RTC/TCPServer.cpp` is a child class of `handles/TCPServer.cpp` specialized in receiving ICE/DTLS/RTP over TCP.

I don't know why this is a problem for you, but there is no error/bug/issue here.

**Comment by saghul** [comment]
IIRC some versions of Visual Studio get confused.

**Comment by Globik** [comment]
VC ++ places all object file in to one folder. If there are two or more  object files with the same names so vc++ takes only one for linking. As a result appeares unresolved symbols)

**Comment by Globik** [comment]
@saghul  then in main.cpp there is also unix specific sigaction.
In a child process the room created but no life in the code on node.js side.
server.createRoom.then(room=>{
console.log("Show me the room",room);
//No luck here, no call, silence, no life
// debug mode is on, child process stdout shows that room is created with id
}).catch(e=>console.log(e));
Error is also in silence
I think in windows that stuff blocks, synchronical 
All is in undefined behavour
Vc compiler warn also on loop.h that the class has virtual functions but not has virtual destructors.

**Comment by ibc** [comment]
> @saghul then in main.cpp there is also unix specific sigaction.

Yes. mediasoup ignores SIGPIPE. Otherwise, when running in Linux, any failure sending over a socket would generate a SIGPIE signal and would close the process.

I don't want to ignore such a signal in the libuv signal handler, because that is slower than just ignoring it via a signal mask.


> In a child process the room created but no life in the code on node.js side.
> server.createRoom(SomeOptionsFromTestDataDirectory).then(room=>{
> console.log("Show me the room",room);
> //No luck here, no call, silence, no life
> // debug mode is on, child process stdout shows that room is created with id
> }).catch(e=>console.log(e));
> Error is also in silence
> I think in windows that uv stuff works synchronically(blocks)
> All is in undefined behavour
> Vc compiler warn also on loop.h that the class has virtual functions but not has virtual destructors.

I would accept PR that makes mediasoup runnable in Windows, but I'm not an expert on that so I cannot spend time on it. If you can do it I would a PR, but that's not something I can support right now.

**Comment by saghul** [comment]
> Yes. mediasoup ignores SIGPIPE. Otherwise, when running in Linux, any failure sending over a socket would generate a SIGPIE signal and would close the process.
> 
> I don't want to ignore such a signal in the libuv signal handler, because that is slower than just ignoring it via a signal mask.

Correct. Since Windows doesn't have the SIGPIPE issue it would be safe to ifdef that.

> I would accept PR that makes mediasoup runnable in Windows, but I'm not an expert on that so I cannot spend time on it. If you can do it I would a PR, but that's not something I can support right now.

I can help with the review, but I don't have the time to write the code myself.

**Comment by Globik** [comment]
Mediasoup is sowieso runnable on windows, just like cinderella. But stdout or what stuff in node.js seems to be blocking process. That feeling that write from mediasoup to node.js end point is blocking or unrunnable. Issue with process.nextTick on nodejs site or Loop::onChannelRequest (sending the answer) to io ' socket'(mediasoup_channel_fd)
By the way getopt.h I am using from...

**Comment by Globik** [comment]
@saghul ,
uv_walk throughout signaling mechanismus of mediasoup can take a place?

**Comment by saghul** [comment]
@Globik I'm afraid we are hitting a language barrier here :-( I don't understand a word of the last 2 comments, sorry.

**Comment by ibc** [comment]
> uv_walk throughout signaling mechanismus of mediasoup can take a place?

I don't know exactly what you mean and what `uv_walk` has to do in here. If you want to propose something because you know it works (also in Windows), just send a PR. But I won't change the mediasoup internal signaling mechanism because it just works in Linux/OSX.
