### ISSUE TITLE
mediasoup.webrtc() just stucks

### ISSUE THREAD

**Issue by notedit** [ibc/mediasoup#37]
i am testing the new webrtc api,  

```
let peerconnection = mediasoup.webrtc(room,'alice',{}); 

```

will just stuck there.

**Comment by notedit** [comment]
may not be stucks,  but i can not see the logs

**Comment by notedit** [comment]
sorry my fault

**Comment by ibc** [comment]
@notedit: the `mediasoup.webrtc` module is not yet documented so I cannot accept issue reports yet. Documentation is in progress but not yet ended:

http://mediasoup.org/api/#webrtc

**Comment by notedit** [comment]
ok   i have already  write  an exmaple.

the chrome webrtc peer can connect with  mediasoup server,  but i can not see  rtp  packet.

there is no error message  in debug message.

waiting  for your docs

**Comment by notedit** [comment]
@ibc   cool  it works

**Comment by ibc** [comment]
Doc has been updated:

http://mediasoup.org/api/#webrtc

However, this is experimental yet.
