### ISSUE TITLE
I can't install mediasoup on ubuntu 14.04 lts

### ISSUE THREAD

**Issue by touch0day** [ibc/mediasoup#43]
5901 verbose stack Error: mediasoup@0.2.0-pre1 postinstall: `make Release`
5901 verbose stack Exit status 2
5901 verbose stack     at EventEmitter.<anonymous> (/root/node-v7.2.1-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
5901 verbose stack     at emitTwo (events.js:106:13)
5901 verbose stack     at EventEmitter.emit (events.js:191:7)
5901 verbose stack     at ChildProcess.<anonymous> (/root/node-v7.2.1-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:40:14)
5901 verbose stack     at emitTwo (events.js:106:13)
5901 verbose stack     at ChildProcess.emit (events.js:191:7)
5901 verbose stack     at maybeClose (internal/child_process.js:885:16)
5901 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
5902 verbose pkgid mediasoup@0.2.0-pre1

**Comment by touch0day** [comment]
[npm-debug.txt](https://github.com/ibc/mediasoup/files/641383/npm-debug.txt)

**Comment by touch0day** [comment]
thanks

**Comment by ibc** [comment]
```
5879 info lifecycle mediasoup@0.2.0-pre1~postinstall: mediasoup@0.2.0-pre1
5880 verbose lifecycle mediasoup@0.2.0-pre1~postinstall: unsafe-perm in lifecycle false
5881 verbose lifecycle mediasoup@0.2.0-pre1~postinstall: PATH: /root/node-v7.2.1-linux-x64/lib/node_modules/npm/bin/node-gyp-bin:/root/node_modules/mediasoup/node_modules/.bin:/root/node_modules/.bin:/root/node-v7.2.1-linux-x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
5882 verbose lifecycle mediasoup@0.2.0-pre1~postinstall: CWD: /root/node_modules/mediasoup
5883 silly lifecycle mediasoup@0.2.0-pre1~postinstall: Args: [ '-c', 'make Release' ]
5884 silly lifecycle mediasoup@0.2.0-pre1~postinstall: Returned: code: 2  signal: null
5885 info lifecycle mediasoup@0.2.0-pre1~postinstall: Failed to exec postinstall script
```

Do you have `make` installed in your system?

**Comment by ibc** [comment]
I just tested mediasoup on Node v7. No errors. Please, comment again if it still fails for you even if you have `make` in your host.

**Comment by touch0day** [comment]
I still can't install in ubuntu 14.04 lts,and I install make in my system


root@iZj6c5gaeh7i73k3v934erZ:~# dpkg -l|grep make
ii  make                                3.81-8.2ubuntu3                   amd64        An utility for Directing compilation.
ii  makedev                             2.3.1-93ubuntu1                   all          creates device files in /dev

**Comment by ibc** [comment]
OK, then I need to see the building errors (there is nothing about it in the logs above). Do this please:

```bash
$
```

**Comment by ibc** [comment]
OK, then I need to see the building errors (there is nothing about it in the logs above). Do this please:

```bash
$ git clone https://github.com/ibc/mediasoup.git

$ cd mediasoup

$ npm install

$ make
```

And paste the output.

**Comment by touch0day** [comment]
It's ok,
when I install like this
but I can't install by npm install mediasoup --save
thank you!

**Comment by ibc** [comment]
I'm sorry, but I tested `npm install mediasoup --save` in a fresh Ubuntu 14.04. It just works.

I still don't know **why** you say that "it fails". I see no real errors in your debug. I don't even know if you are trying to install it as root, with sudo, etc etc.

After you run `npm install mediasoup --save`, do you see a `node_modules/mediasoup/` in your folder? And can you run this?:

```bash
$ node

node> var mediasoup = require("mediasoup");
```

I don't even know whether you are installing mediasoup within your existing Node application or you just think that mediasoup is an standalone server that must be installed via `npm install mediasoup ---save` and it automatically runs or whatever.

I'm sorry but you provide zero info and I cannot help with just that.

**Comment by touch0day** [comment]
thanks 
It's working now
I am trying to connect to mediasoup from my normal webrtc 1.0 client 
I am using kurento for my system,but my server CPU is high level 
so I try to change media server to mediasoup
I will setup a new signal server,but I don't know how can I integrate the signal server and mediasoup
If somewhere have some examples,It will be perfect!
thank you!

**Comment by ibc** [comment]
There is an example in the API documentation. I cannot provide more than that. The API is as easy as the one provided by WebRTC in the browser.
