### ISSUE TITLE
Can I connect mediasoup with browser

### ISSUE THREAD

**Issue by RonieLiu** [ibc/mediasoup#44]
I need browser client A push mediastream to mediasoup ,then mediasoup send the mediasteam to browser client B,but I can't  connect mediasoup with browser. Broswer use ice-full ,but mediasoup use ice-lite,so,I don't know how to use ice-lite in brower.

**Comment by saghul** [comment]
Browsers definitely work with mediasoup.  You shouldn't need to do anything, because the browser will take the ICE controlling agent role, as mediasoup uses a lite implementation and thus will take the role of a controlled agent.

**Comment by ibc** [comment]
The SDP generated by mediasoup has a=ice-lite.

**Comment by RonieLiu** [comment]
en,thank you
