### ISSUE TITLE
Communicate with another mediasoup ?

### ISSUE THREAD

**Issue by SwordLonn** [ibc/mediasoup#45]
Did ice lite implementation has ability that connect with other lite implements?
Or can mediasoup communicate with another one?

**Comment by ibc** [comment]
Please, let's use the [mailing list](http://mediasoup.org/support/) for questions. This is the issue tracker.

BTW the scenario you suggest is not feasible right now. *mediasoup* can just talk to full-ICE implementations. I may add this ability in the future, but not right now.

**Comment by SwordLonn** [comment]
Sorry for that.

BTW, It will be a great thing, thank you.
