### ISSUE TITLE
Recv video delay

### ISSUE THREAD

**Issue by ibc** [ibc/mediasoup#58]
So many times, the video receipt is delayed 3-4 seconds (the audio is not). Something is wrong somewhere.

`chrome://webrtc-internals` clearly shows a huge delay in the received video:

```
cname:igdI6A7KO49Laewo
msid:n2BD8WybHYhbmadosp9qG4hwSMiNkDFg5pEb 014a29c1-e5cc-4267-bb34-9ac4d2fec934
mslabel:n2BD8WybHYhbmadosp9qG4hwSMiNkDFg5pEb
label:014a29c1-e5cc-4267-bb34-9ac4d2fec934
timestamp	11/2/2017 16:38:15
bytesReceived	31885384
codecImplementationName	libvpx
framesDecoded	8431
mediaType	video
packetsLost	23
packetsReceived	31199
ssrc	3507811542
transportId	Channel-audio-tracks-1
googCaptureStartNtpTimeMs	3695807408228
googCodecName	VP8
googCurrentDelayMs	3053
googDecodeMs	3
googFirsSent	0
googFrameHeightReceived	360
googFrameRateDecoded	30
googFrameRateOutput	30
googFrameRateReceived	18
googFrameWidthReceived	480
googJitterBufferMs	3038
googMaxDecodeMs	5
googMinPlayoutDelayMs	0
googNacksSent	57
googPlisSent	13
googRenderDelayMs	10
googTargetDelayMs	3053
googTrackId	014a29c1-e5cc-4267-bb34-9ac4d2fec934
```

**Comment by ibc** [comment]
Reopen. It still happens. No idea.

**Comment by ibc** [comment]
If we filter RR for video (so RR is not generated for video streams), the issue does not happen.

**Comment by ibc** [comment]
Some (related?) links:

* https://tokbox.com/blog/lip-sync-issues-when-a-chrome-update-fixes-your-application/
* https://bugs.chromium.org/p/webrtc/issues/detail?id=5456
* https://groups.google.com/forum/#!topic/discuss-webrtc/qxpJ6PyUaEQ
* https://bugs.chromium.org/p/webrtc/issues/detail?id=4355
* https://bugs.chromium.org/p/webrtc/issues/detail?id=6213

NOTE: Most of these links are related to paused/resumed video tracks, which is not our current scenario.

**Comment by jmillan** [comment]
TODO for me: RtpStream unit tests.

**Comment by jmillan** [comment]
AFAIK, this has been fixed today. 8d01e1607c2, 1cb9703

Anyway lets keep it open until RtpStream tests are done

**Comment by ibc** [comment]
@jmillan can we close it? or do you mean that you prefer to add some test units to check the RR and SR timestamp related values before closing it?

**Comment by jmillan** [comment]
We can close it @ibc. Current reports are correctly generated. I'd like to make the tests richer but we don't need to keep the issue open for it. Current tests do already do the job.

**Comment by ibc** [comment]
OK, closing then (and one issue less)
