### ISSUE TITLE
Wrong usage of uv_now()

### ISSUE THREAD

**Issue by ibc** [ibc/mediasoup#59]
As @saghul told me, `uv_now()` does not return the current time:

```
uint64_t uv_now(const uv_loop_t* loop)

Return the current timestamp in milliseconds. The timestamp is cached at the start of the event loop tick, see uv_update_time() for details and rationale.

The timestamp increases monotonically from some arbitrary point in time. Don’t make assumptions about the starting point, you will only get disappointed.
```

It seems that libuv does not provide an API to get the current time, so we must directly use [gettimeofday()](http://man7.org/linux/man-pages/man2/gettimeofday.2.html).

**Comment by ibc** [comment]
We can use `uv_now()` (or `uv_hrtime()`for sub-millisecond granularity) just to get the difference between two moments.

**Comment by jmillan** [comment]
The fact that it increases monotonically is what matters us (for now). We are just getting time differences. 

I think we can close this issue. Whenever it comes to get the real time, we'll have to use `gettimeofday` for example, as you point.

**Comment by ibc** [comment]
> The fact that it increases monotonically is what matters us (for now). We are just getting time differences.

Are you completely sure? In `RTC/RtpStreamRecv.cpp` I see:

```c++
uint32_t delayMs = (DepLibUV::GetTime() - this->last_sr_received);

this->last_sr_received = DepLibUV::GetTime();
```

That seems OK as, in fact, that's a time difference.

```c++
int transit = DepLibUV::GetTime() - (rtpTimestamp * 1000 / this->clockRate);
```

And this i also used to calculate time differences.

So yes, sorry I was checking it while writing this response :)
