### ISSUE TITLE
Smart REMB handling

### ISSUE THREAD

**Issue by ibc** [ibc/mediasoup#60]
Generate REMB estimations for remote senders based on the estimated bandwidth of each remote peer receiving its streams.

The algorithm must accomplish with some goals:

* If there are just two participants in the room (A and B), and all the streams from A are being sent to B, and mediasoup receives a REMB from B indicating a bandwidth estimation of XXXX kbits, then the REMB mediasoup generates for A should be ~XXXX kbits.
* If there are more than 2 participants in the room, the algorithm must generate REMB values to make most of the receivers happy without limiting too much the upload bandwidth (this is, if there is a participant with a very poor download bandwidth, the algorithm must not exaggeratedly produce very low REMB values.

**Comment by ibc** [comment]
After a chat with @jmillan it seems that the above strategy is not so good. Rather we'll develop an algorithm to generate REMB estimations for remote senders based on the estimated bandwidth of each receiver.

**Comment by ibc** [comment]
I've just sent an email to the RMCAT IETF Working Group asking some doubts regarding REMB:

----

It's not clear for me what the "SSRC feedback" entries in the REMB message mean. According to the [draft](https://tools.ietf.org/html/draft-alvestrand-rmcat-remb-03):

> Num SSRC (8 bits):  Number of SSRCs in this message.
> SSRC feedback (32 bits): Consists of one or more SSRC entries which this feedback message applies to.

At the same time, the draft says:

> This feedback message is used to notify a sender of multiple media
streams over the same RTP session of the total estimated available
bit rate on the path to the receiving side of this RTP session.

The meaning of "RTP session" is hard to explain nowadays, so I'll assume it means "a media transport" (which in the context of WebRTC points to an ICE established "connection" which can carry multiple SSRC streams).

So, if for example Alice is receiving audio (SSRC 1111) and video (SSRC 2222) over a BUNDLEd transport, and assuming Alice can just receive 500 kbits/s, how should REMB messages generated by Alice look like?

Should these REMB messages contain both SSRC 1111 and SSRC 2222 and indicate 500000 as media bit rate?

What would happen if Alice sends a REMB just including the SSRC 1111 and 500000 as media bit rate? Should Bob limit its audio bitrate up to 500kbit/s and send whatever he wants regarding its video stream?

**Comment by ibc** [comment]
I've found this [text](https://mailarchive.ietf.org/arch/msg/rmcat/t71fzDtaQatyi2yA9wa0yRfhXHI):

>> the maximum bitrate, is it defined as the maximum bitrate for  a particular stream, or the maximum bitrate for the whole "Session"?

> It depends on how many and which SSRCs are reported in the feedback message. As per the draft, it is up to the implementation (or the congestion control algorithm) to choose which SSRCs, i.e., it could report just the SSRCs of audio or video or a combination.

**Comment by ibc** [comment]
Response from Harald:

> The way it was originally designed, it meant that the total should be
100 Kbits/sec. REMB did not take a position on how the sender chose to
allocate bits between the SSRCs, only the total amount of bits sent.

**Comment by ibc** [comment]
NOTE: This may be not done. Simulcast/SVC seems the only way to go.

**Comment by jmillan** [comment]
Remote bitrate estimation and REMB generation is already being accomplished as by the Google Congestion Control algorithm.  in branch remote-bitrate-estimator.

I think we can close this issue.

**Comment by ibc** [comment]
I prefer to wait until merged into master :)

BTW: This issue is also about processing REMB from endpoints and having them influencing into the REMB `bitrate` generated by mediasoup. May we wait until that is also done before closing the issue?

**Comment by ibc** [comment]
Let's close this. May reopen later if we really want to do "magic" with received REMB packets to influence our remote senders.
