### ISSUE TITLE
RTCP BYE ssrc is stored in host Host Byte Order

### ISSUE THREAD

**Issue by ibc** [ibc/mediasoup#68]
In `ByePacket::Parse()`:

```c++
packet->AddSsrc(ntohl(Utils::Byte::Get4Bytes(data, offset)));
```

So the ssrc is stored in host byte order. `Dump()` does not change that.

However printed SSRC values are wrong (tested). For example, this is the SSRC sent by the browser:

```
a=ssrc:935183265
```

And this is the mediasoup dump when a BYE is received:

```
RTC::RTCP::Bye::Dump() | <ByePacket> +0ms
RTC::RTCP::Bye::Dump() |   ssrc   : 3329508425 +0ms
RTC::RTCP::Bye::Dump() | </ByePacket> +0ms
```

Then, the `ByePacket::Serialize()` also does byte order conversion stuff... I think it's better to always store the ssrc values in network byte order.

**Comment by ibc** [comment]
What I don't understand is why `Dump()` prints a wrong value (in network order). If I use `htonl(ssrc)` within the `Dump()` method, it correctly displays the value.

**Comment by ibc** [comment]
`Utils::Byte::Get4Bytes()` returns a `uint32_t` in host byte order, agreed?. The inline doc in that method is wrong.

**Comment by jmillan** [comment]
Right, Get4Bytes makes the conversion to host byte order.

**Comment by ibc** [comment]
OK. BTW I see that in other files, such as in `StunMessage` I get some fields using `GetXBytes()` (for example `this->priority`) and it's stored as it, in host byte order. So may be it's not bad to store ssrcs of Bye in host byte order (in fact it's better since the class exposes the vector iterator).

I think we'd just should store values in network byte order when the value is got from a stored C struct (such as in RTP and RTCP packets).

**Comment by jmillan** [comment]
They are stored in host by order. That was the intention.

I'm just removing the htonl|ntohl funcitons. Just need to test it :-)
