### ISSUE TITLE
Implement backpressure in TCP/UDP

### ISSUE THREAD

**Issue by ibc** [ibc/mediasoup#7]
libuv offers (now) public API to check the write/send queue size (in bytes). So:
- Add a setter `SetBackPressure(value)`.
- When in `Write()` or `Send()` check if such a value is greater than the handle write/send queue.
- If so call `listener->onBackPressureExceeded(current_value)`.

**Comment by ggarber** [comment]
Is this a protection in case REMB is not working/fast-enough ?  Or some specific use case where you  have very small buffers for some reason?   I haven't seen this as an issue so far with real customers.

**Comment by ibc** [comment]
This feature works at pure transport level (UDP or TCP). libuv API allows the app to check the outgoing buffer of a socket handler. This can tell whether the app is trying to send data faster than what the network can absorb.

And yes, this should never be an issue. I just keep this issue as "documentation" :)

Better let's close it.
