### ISSUE TITLE
one peer join the room, how can he only receive all the stream, but he don't send any stream, he is the role of monitore

### ISSUE THREAD

**Issue by touch0day** [ibc/mediasoup#81]
I am researching mediasoup system 
but we have a role of monitor
so the role join the room but no stream upload, and receive all the streams of the room

**Comment by ibc** [comment]
Please, let's use the public mailing list for usage questions:

https://mediasoup.org/support/

Your use case has no mystery at all. Just make the monitor join the room without attaching any local `MediaStream` into its `PeerConnection` (in the browser I mean).

**Comment by touch0day** [comment]
thank you very much
