### ISSUE TITLE
Makefile: Python 2 detection fails

### ISSUE THREAD

**Issue by ibc** [ibc/mediasoup#84]
Related to #82, it was theoretically fixed in 0643a484037e85d9ae543772196aa055f38a0adf, but then Travis-CI failed:

* https://travis-ci.org/ibc/mediasoup/jobs/216526868

```
> make Release

cd worker && -p: not found python2 is /opt/python/2.7.12/bin/python2 python ./scripts/configure.py -R mediasoup-worker

/bin/sh: 1: -p:: not found
make: *** [Release] Error 127
```

**Comment by saghul** [comment]
Try this:

```
PYTHON ?= $(shell command -v python2 2> /dev/null || echo python)
```

**Comment by ibc** [comment]
Yes @saghul ! 3f00421ef3fe18bfe6f5e4d93cf7c7343fc5f192  worked! Thanks!

**Comment by saghul** [comment]
Awesome! 🍸
